name: Deploy to cPanel

on:
  push:
    branches:
      - main # Sesuaikan jika nama branch kamu 'master'

jobs:
  web-deploy:
    name: Deploy Website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install Dependencies & Build Vite Assets
        run: |
          npm ci
          npm run build

      - name: Sync Files via FTP
        uses: SamKirkland/ftp-deploy-action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          server-dir: /public_html/
          exclude: |
            **/node_modules/**
            **/.git*/**