name: Deploy to cPanel

on:
  push:
    branches:
      - main # Sesuaikan jika nama branch utama kamu 'master'

jobs:
  web-deploy:
    name: Deploy Website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Sync Files via FTP
        uses: SamKirkland/ftp-deploy-action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /public_html/